version: '3.9'

services:
  database-dev:
    image: postgres-vector
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: localdev
      POSTGRES_DB: backenddb
    ports:
      - '5433:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    container_name: database-dev
    restart: always

volumes:
  pgdata:
    driver: local
